"""CMake feature plugin and its transport-neutral public API."""

from forgemcp.cmake.errors import (
    CMakeBuildTreeIncompatibleError,
    CMakeError,
    CMakeFileApiError,
    CMakeKitError,
    CMakeKitSelectionConflictError,
    CompilationDatabaseRequirementError,
    CMakePresetError,
    CMakePresetKitConflictError,
    CMakeRequestError,
    CMakeToolUnavailableError,
    CMakeVersionError,
    CTestJsonError,
)
from forgemcp.cmake.models import (
    CMakeBuildPreset,
    CMakeBuildResult,
    CMakeBuildTree,
    CMakeBuildTreeList,
    CMakeConfigurationTargets,
    CMakeConfigurePreset,
    CMakeConfigureResult,
    CMakeDiagnostic,
    CMakePresetList,
    CMakeResolvedProfile,
    CMakeStatus,
    CMakeTargetList,
    CMakeTargetMetadata,
    CMakeTestPreset,
    CMakeToolStatus,
    CMakeVersion,
    CompilationDatabaseStatus,
    CTestRunResult,
    CTestTest,
    CTestTestList,
)
from forgemcp.cmake.plugin import CMakePlugin
from forgemcp.cmake.events import CompilationDatabaseRegistry, CompilationDatabaseSubscription
from forgemcp.cmake.service import CMakeService, MAX_PARALLEL_JOBS, MINIMUM_CMAKE_VERSION
from forgemcp.toolchain import CMakeKit, CMakeKitList, CMakeKitSelection, ToolchainProfile

__all__ = [
    "CMakeBuildPreset",
    "CMakeBuildResult",
    "CMakeBuildTree",
    "CMakeBuildTreeList",
    "CMakeBuildTreeIncompatibleError",
    "CMakeConfigurationTargets",
    "CMakeConfigurePreset",
    "CMakeConfigureResult",
    "CMakeDiagnostic",
    "CMakeError",
    "CMakeFileApiError",
    "CMakeKit",
    "CMakeKitError",
    "CMakeKitList",
    "CMakeKitSelection",
    "CMakeKitSelectionConflictError",
    "CMakePlugin",
    "CompilationDatabaseRegistry",
    "CompilationDatabaseSubscription",
    "CMakePresetError",
    "CMakePresetKitConflictError",
    "CMakePresetList",
    "CMakeResolvedProfile",
    "CMakeRequestError",
    "CMakeService",
    "CMakeStatus",
    "CMakeTargetList",
    "CMakeTargetMetadata",
    "CMakeTestPreset",
    "CMakeToolStatus",
    "CMakeToolUnavailableError",
    "CMakeVersion",
    "CompilationDatabaseStatus",
    "CompilationDatabaseRequirementError",
    "CMakeVersionError",
    "CTestJsonError",
    "CTestRunResult",
    "CTestTest",
    "CTestTestList",
    "MAX_PARALLEL_JOBS",
    "MINIMUM_CMAKE_VERSION",
    "ToolchainProfile",
]
