"""CMake feature plugin and its transport-neutral public API."""

from forgemcp.cmake.errors import (
    CMakeError,
    CMakeFileApiError,
    CompilationDatabaseRequirementError,
    CMakePresetError,
    CMakeRequestError,
    CMakeToolUnavailableError,
    CMakeVersionError,
    CTestJsonError,
)
from forgemcp.cmake.models import (
    CMakeBuildPreset,
    CMakeBuildResult,
    CMakeConfigurationTargets,
    CMakeConfigurePreset,
    CMakeConfigureResult,
    CMakePresetList,
    CMakeResolvedProfile,
    CMakeStatus,
    CMakeTargetList,
    CMakeTargetMetadata,
    CMakeTestPreset,
    CMakeToolStatus,
    CMakeVersion,
    CompilationDatabaseStatus,
    CTestRunResult,
    CTestTest,
    CTestTestList,
)
from forgemcp.cmake.plugin import CMakePlugin
from forgemcp.cmake.events import CompilationDatabaseRegistry, CompilationDatabaseSubscription
from forgemcp.cmake.service import CMakeService, MAX_PARALLEL_JOBS, MINIMUM_CMAKE_VERSION

__all__ = [
    "CMakeBuildPreset",
    "CMakeBuildResult",
    "CMakeConfigurationTargets",
    "CMakeConfigurePreset",
    "CMakeConfigureResult",
    "CMakeError",
    "CMakeFileApiError",
    "CMakePlugin",
    "CompilationDatabaseRegistry",
    "CompilationDatabaseSubscription",
    "CMakePresetError",
    "CMakePresetList",
    "CMakeResolvedProfile",
    "CMakeRequestError",
    "CMakeService",
    "CMakeStatus",
    "CMakeTargetList",
    "CMakeTargetMetadata",
    "CMakeTestPreset",
    "CMakeToolStatus",
    "CMakeToolUnavailableError",
    "CMakeVersion",
    "CompilationDatabaseStatus",
    "CompilationDatabaseRequirementError",
    "CMakeVersionError",
    "CTestJsonError",
    "CTestRunResult",
    "CTestTest",
    "CTestTestList",
    "MAX_PARALLEL_JOBS",
    "MINIMUM_CMAKE_VERSION",
]
