"""Public transport-neutral API for ForgeMCP's managed clangd feature."""

from forgemcp.clangd.errors import (
    ClangdContentModifiedError,
    ClangdEditConflictError,
    ClangdError,
    ClangdFailedError,
    ClangdHandleExpiredError,
    ClangdNotStartedError,
    ClangdProtocolError,
    ClangdRequestCancelledError,
    ClangdRequestError,
    ClangdTimeoutError,
    ClangdUnavailableError,
    ClangdUnsupportedActionError,
    ClangdUnsupportedWorkspaceEditError,
)
from forgemcp.clangd.models import (
    CallHierarchyItem,
    CallHierarchyPrepareResult,
    ClangdSessionState,
    ClangdStartResult,
    ClangdStatus,
    CodeActionResult,
    CodeActionSummary,
    CompletionInsertTextFormat,
    CompletionItem,
    CompletionResult,
    CompletionTextEdit,
    DocumentDiagnosticsResult,
    DocumentSymbol,
    DocumentSymbolsResult,
    FormatResult,
    HoverResult,
    IncomingCall,
    IncomingCallsResult,
    NavigationResult,
    OutgoingCall,
    OutgoingCallsResult,
    RenamePreparation,
    RenameResult,
    SignatureHelpResult,
    SignatureInformation,
    SwitchSourceHeaderResult,
    TypeHierarchyItem,
    TypeHierarchyPrepareResult,
    TypeHierarchyResult,
    WorkspaceEditSummary,
    WorkspaceLocation,
    WorkspaceSymbol,
    WorkspaceSymbolsResult,
)
from forgemcp.clangd.plugin import ClangdPlugin
from forgemcp.clangd.service import ClangdService

__all__ = [
    "CallHierarchyItem", "CallHierarchyPrepareResult", "ClangdContentModifiedError", "ClangdEditConflictError",
    "ClangdError", "ClangdFailedError", "ClangdHandleExpiredError", "ClangdNotStartedError", "ClangdPlugin",
    "ClangdProtocolError", "ClangdRequestCancelledError", "ClangdRequestError", "ClangdService", "ClangdSessionState",
    "ClangdStartResult", "ClangdStatus", "ClangdTimeoutError", "ClangdUnavailableError", "ClangdUnsupportedActionError",
    "ClangdUnsupportedWorkspaceEditError", "CodeActionResult", "CodeActionSummary", "CompletionInsertTextFormat",
    "CompletionItem", "CompletionResult", "CompletionTextEdit", "DocumentDiagnosticsResult", "DocumentSymbol", "DocumentSymbolsResult",
    "FormatResult", "HoverResult", "IncomingCall", "IncomingCallsResult", "NavigationResult", "OutgoingCall",
    "OutgoingCallsResult", "RenamePreparation", "RenameResult", "SignatureHelpResult", "SignatureInformation",
    "SwitchSourceHeaderResult", "TypeHierarchyItem", "TypeHierarchyPrepareResult", "TypeHierarchyResult", "WorkspaceEditSummary",
    "WorkspaceLocation", "WorkspaceSymbol", "WorkspaceSymbolsResult",
]
