const MAX_TEXT = 1024;
const MAX_ITEMS = 500;
const root = document.getElementById("app");
function isObject(value) { return value !== null && typeof value === "object" && !Array.isArray(value); }
function safeText(value, maximum = MAX_TEXT) { if (typeof value !== "string") return ""; const bounded = value.slice(0, maximum); return bounded.replace(/[\u0000-\u001f\u007f-\u009f\u202a-\u202e\u2066-\u2069]/gu, (item) => `\\u${item.codePointAt(0).toString(16).padStart(4, "0")}`) + (value.length > maximum ? "…" : ""); }
function count(value, maximum = MAX_ITEMS) { return Number.isInteger(value) && value >= 0 && value <= maximum ? value : 0; }
function el(tag, className, text) { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node; }
function resultPayload(result) { if (!isObject(result) || result.isError === true) return null; if (isObject(result.structuredContent)) return result.structuredContent; const item = Array.isArray(result.content) && result.content.length === 1 && isObject(result.content[0]) ? result.content[0] : null; if (typeof item?.text !== "string" || item.text.length > 100000) return null; try { const parsed = JSON.parse(item.text); return isObject(parsed) ? parsed : null; } catch { return null; } }
function location(value) { if (!isObject(value) || typeof value.path !== "string" || !isObject(value.range)) return null; return { path: safeText(value.path), range: safeText(JSON.stringify(value.range), 128) }; }
function shell(title, summary, rows, detail, state = "complete") { root.replaceChildren(); const panel = el("section", "forge-clangd"); panel.setAttribute("aria-label", `clangd ${title}`); const head = el("header", "forge-head"); head.append(el("span", "forge-prompt", "$"), el("span", "forge-title", `clangd::${title}`)); panel.append(head); panel.append(summary); const list = el("ul", "forge-list"); if (!rows.length) list.append(el("li", "forge-muted", "No safe result items.")); for (const row of rows) list.append(row); panel.append(list); const detailRow = el("div", "forge-detail"); detailRow.setAttribute("aria-live", "polite"); detailRow.append(el("span", "forge-detail-label", "detail:"), el("span", "forge-detail-main", detail[0]), el("span", "forge-detail-extra", detail[1])); panel.append(detailRow); const foot = el("footer", "forge-foot"); foot.append(el("span", "forge-muted", "local view · no actions"), el("span", state === "complete" ? "forge-ok" : "forge-warn", `${state === "complete" ? "●" : "!"} ${state}`)); panel.append(foot); root.append(panel); }
function selectable(label, kind, meta, select) { const item = el("li"); const row = el("button", "forge-row"); row.type = "button"; row.setAttribute("aria-selected", "false"); row.append(el("span", "forge-row-kind", safeText(kind, 18)), el("span", "forge-row-text", safeText(label)), el("span", "forge-row-meta", safeText(meta, 160))); row.addEventListener("click", () => select(row)); item.append(row); return item; }
