import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
const sourceDirectory=dirname(fileURLToPath(import.meta.url)), root=join(sourceDirectory,"..",".."), common=join(sourceDirectory,"..","common"), frontend=join(sourceDirectory,"..");
const names=[["catalog","catalog-app.js"],["operation","operation-app.js"]];
const normalize=value=>value.replace(/\r\n?/g,"\n");
const [template,theme,css,helper,runtime]=await Promise.all(["template.html",join(common,"theme.css"),"cmake-app.css",join(common,"mcp-app.js"),join(frontend,"node_modules","@modelcontextprotocol","ext-apps","dist","src","app-with-deps.js")].map(path=>readFile(path.includes("/")||path.includes("\\")?path:join(sourceDirectory,path),"utf8")));
const exports=["App","PostMessageTransport","applyDocumentTheme","applyHostFonts","applyHostStyleVariables"], match=/export\{(?<exports>[\s\S]+)\};?\s*$/u.exec(runtime); if(!match?.groups?.exports)throw new Error("official runtime export block missing"); const aliases=Object.fromEntries(exports.map(name=>{const found=new RegExp(`(?:^|,)\\s*(\\w+) as ${name}(?=,|$)`,"u").exec(match.groups.exports);if(!found)throw new Error(`runtime export missing: ${name}`);return[name,found[1]];}));
const runtimeCode=normalize(runtime.slice(0,match.index))+`globalThis.__forgemcpExtApps=Object.freeze({${exports.map(name=>`${name}:${aliases[name]}`).join(",")}});\n`; const helperCode=normalize(helper).replace(/import\s*\{[\s\S]*?\}\s*from "@modelcontextprotocol\/ext-apps";\s*/u,()=>`const {${exports.join(",")}}=globalThis.__forgemcpExtApps;\n`).replace(/export\s+(?=function\s)/gu,"");
for(const [name,source] of names){const app=normalize(await readFile(join(sourceDirectory,source),"utf8")).replace(/import\s*\{\s*connectMcpApp\s*\}\s*from "\.\.\/common\/mcp-app\.js";\s*/u,"");const javascript=`${runtimeCode}(()=>{\n${helperCode}${app}\n})();\n`.replace(/[ \t]+(?=\r?\n)/g,"").replaceAll("</script","<\\/script"), base=normalize(template), html=base.replace("/* APP_CSS */",()=>`${normalize(theme)}\n${normalize(css)}`).replace("/* APP_JS */",()=>javascript).replace("<!doctype html>",`<!doctype html><!-- source-sha256:${createHash("sha256").update(base).update(normalize(theme)).update(normalize(css)).update(javascript).digest("hex")} -->`), output=join(root,"src","forgemcp","apps","assets",`cmake-${name}.html`);if(process.argv.includes("--write"))await writeFile(output,html,"utf8");else if(normalize(await readFile(output,"utf8"))!==html)throw new Error(`cmake-${name}.html is stale; run build.mjs --write`);}
