import { connectMcpApp } from "../common/mcp-app.js";
const MAX_ITEMS = 160, MAX_TEXT = 256;
const state = { data: null, selected: null, tornDown: false };
const text = (value, limit = MAX_TEXT) => typeof value === "string" && value.length <= limit && !/[\x00-\x1f\x7f]/.test(value) ? value : "—";
const payload = (value) => { if (value && typeof value === "object" && value.structuredContent && typeof value.structuredContent === "object") return value.structuredContent; if (value && typeof value === "object" && Array.isArray(value.content) && typeof value.content[0]?.text === "string") { try { const parsed = JSON.parse(value.content[0].text); return parsed && typeof parsed === "object" ? parsed : null; } catch { return null; } } return value && typeof value === "object" ? value : null; };
function rows(data) { const candidates = data?.kits || data?.build_trees || data?.configure_presets || data?.tests; if (Array.isArray(candidates)) return candidates.slice(0, MAX_ITEMS).filter(item => item && typeof item === "object"); if (Array.isArray(data?.configurations)) return data.configurations.flatMap(c => Array.isArray(c?.targets) ? c.targets.map(t => ({ ...t, configuration: c.name })) : []).slice(0, MAX_ITEMS); if (data && typeof data === "object") return [data]; return []; }
const el = (tag, className, value) => { const node = document.createElement(tag); node.className = className; node.textContent = value; return node; };
function label(item) { return text(item.name || item.id || item.profile_id || item.binary_dir || item.source_dir || item.available === true && "available" || "result"); }
function detail(item) { return text(item.type || item.readiness || item.generator || item.availability || item.description || item.binary_dir || "no additional metadata"); }
function render() { const root = document.getElementById("app"); root.replaceChildren(); const data = state.data, list = rows(data), selected = state.selected || list[0] || null; const term = el("section", "term", ""); term.append(el("header", "head", "› cmake catalog")); const summary = el("div", "summary", ""); summary.append(el("span", data ? "ok" : "warn", data ? "● received" : "● waiting"), el("span", "title", data ? text(data.binary_dir || data.source_dir || "safe result") : "Run a CMake catalog tool"), el("span", "muted", `${list.length}${list.length === MAX_ITEMS ? "+" : ""} rows`)); term.append(summary); const listNode = document.createElement("ul"); listNode.className = "rows"; if (!list.length) listNode.append(el("li", "muted", data ? "No safe rows returned." : "Waiting for a tool result.")); for (const item of list) { const li = document.createElement("li"), button = document.createElement("button"); button.type = "button"; button.className = "row"; button.setAttribute("aria-selected", String(item === selected)); button.append(el("span", "ok", "·"), el("span", "cell", label(item)), el("span", "cell muted", detail(item))); button.addEventListener("click", () => { state.selected = item; render(); }); button.addEventListener("focus", () => { state.selected = item; render(); }); li.append(button); listNode.append(li); } term.append(listNode); const strip = el("div", "detail", ""); strip.append(el("span", "muted", "preview"), el("span", "detail-value", selected ? `${label(selected)} · ${detail(selected)}` : "—")); term.append(strip); term.append(el("footer", "foot muted", "CMake metadata only · no command or path output")); root.append(term); }
connectMcpApp({ name:"forgemcp-cmake-catalog", ontoolinput:()=>{}, ontoolresult:(result)=>{ state.data=payload(result); state.selected=null; render(); }, onhostcontextchanged:()=>{}, onteardown:()=>{state.tornDown=true;} }).catch(()=>{if(!state.tornDown)render();}); render();
