import { connectMcpApp } from "../common/mcp-app.js";
const MAX_DIAGNOSTICS = 80, MAX_TEXT = 256;
const state = { data:null, selected:null, tornDown:false };
const text=(v)=>typeof v === "string" && v.length <= MAX_TEXT && !/[\x00-\x1f\x7f]/.test(v) ? v : "—";
const payload=(v)=>{ if(v&&typeof v==="object"&&v.structuredContent&&typeof v.structuredContent==="object")return v.structuredContent; if(v&&typeof v==="object"&&Array.isArray(v.content)&&typeof v.content[0]?.text==="string"){try{const p=JSON.parse(v.content[0].text);return p&&typeof p==="object"?p:null;}catch{return null;}} return v&&typeof v==="object"?v:null; };
const el=(tag,cls,value)=>{const n=document.createElement(tag);n.className=cls;n.textContent=value;return n;};
function outcome(data){ const code=data?.process?.exit_code; if(!data)return ["waiting","warn"]; if(data?.outcome&&data.outcome!=="success")return [text(data.outcome),"bad"]; if(code===0)return ["success","ok"]; if(typeof code==="number")return ["tool execution failed","bad"]; return ["transport or malformed result","bad"]; }
function render(){const root=document.getElementById("app"),data=state.data,diagnostics=Array.isArray(data?.diagnostics)?data.diagnostics.slice(0,MAX_DIAGNOSTICS).filter(d=>d&&typeof d==="object"):[],selected=state.selected||diagnostics[0]||null,[status,color]=outcome(data);root.replaceChildren();const term=el("section","term","");term.append(el("header","head","› cmake operation"));const summary=el("div","summary","");summary.append(el("span",color,`● ${status}`),el("span","title",text(data?.binary_dir||data?.kit||"result")),el("span","muted",typeof data?.process?.duration_milliseconds==="number"?`${data.process.duration_milliseconds} ms`:"") );term.append(summary);const list=document.createElement("ul");list.className="rows";if(!diagnostics.length)list.append(el("li","muted",data?"No normalized diagnostics returned.":"Waiting for a tool result."));for(const item of diagnostics){const li=document.createElement("li"),button=document.createElement("button");button.type="button";button.className="row";button.setAttribute("aria-selected",String(item===selected));button.append(el("span",item.severity==="error"?"bad":item.severity==="warning"?"warn":"ok",item.severity==="error"?"!":"·"),el("span","cell",text(item.message)),el("span","cell muted",text(item.file||item.category||"diagnostic")));button.addEventListener("click",()=>{state.selected=item;render();});button.addEventListener("focus",()=>{state.selected=item;render();});li.append(button);list.append(li);}term.append(list);const strip=el("div","detail","");strip.append(el("span","muted","location"),el("span","detail-value",selected?`${text(selected.file||"workspace location unavailable")} · ${text(selected.message)}`:"No selectable diagnostic"));term.append(strip);term.append(el("footer","foot muted","Normalized diagnostics only · no raw output or command data"));root.append(term);}
connectMcpApp({name:"forgemcp-cmake-operation",ontoolinput:()=>{},ontoolresult:(result)=>{state.data=payload(result);state.selected=null;render();},onhostcontextchanged:()=>{},onteardown:()=>{state.tornDown=true;}}).catch(()=>{if(!state.tornDown)render();});render();
