"""Public feature-plugin API for ForgeMCP extensions."""

from forgemcp.plugins.contract import (
    PLUGIN_API_VERSION,
    ForgePlugin,
    PluginContext,
    PluginLogger,
    PluginMetadata,
    PluginServiceAccess,
)
from forgemcp.plugins.errors import (
    DuplicateCapabilityError,
    DuplicatePluginIdError,
    DuplicateToolNameError,
    MissingPluginDependencyError,
    MissingRequiredServiceError,
    PluginApiVersionError,
    PluginDependencyCycleError,
    PluginDiscoveryError,
    PluginError,
    PluginManagerClosedError,
    PluginRegistrationError,
    PluginStartError,
    ToolNamespaceError,
)
from forgemcp.plugins.manager import PluginManager, PluginState, PluginStatus
from forgemcp.plugins.tools import (
    ContextAwareToolHandler,
    LegacyToolHandler,
    PluginToolRegistry,
    RegisteredToolContribution,
    ToolHandler,
    ToolContribution,
    ToolRegistry,
    handler_accepts_execution_context,
    invoke_tool_handler,
)
from forgemcp.plugins.execution import (
    MAX_PROGRESS_MESSAGE_CHARACTERS,
    NoOpProgressReporter,
    ProgressReporter,
    ProgressUpdate,
    ToolExecutionContext,
)

__all__ = [
    "PLUGIN_API_VERSION",
    "ContextAwareToolHandler",
    "DuplicateCapabilityError",
    "DuplicatePluginIdError",
    "DuplicateToolNameError",
    "ForgePlugin",
    "MissingPluginDependencyError",
    "MissingRequiredServiceError",
    "PluginApiVersionError",
    "PluginContext",
    "PluginDependencyCycleError",
    "PluginDiscoveryError",
    "PluginError",
    "PluginManager",
    "PluginManagerClosedError",
    "PluginMetadata",
    "PluginLogger",
    "PluginRegistrationError",
    "PluginServiceAccess",
    "PluginStartError",
    "PluginState",
    "PluginStatus",
    "PluginToolRegistry",
    "LegacyToolHandler",
    "MAX_PROGRESS_MESSAGE_CHARACTERS",
    "NoOpProgressReporter",
    "ProgressReporter",
    "ProgressUpdate",
    "RegisteredToolContribution",
    "ToolContribution",
    "ToolExecutionContext",
    "ToolHandler",
    "ToolNamespaceError",
    "ToolRegistry",
    "handler_accepts_execution_context",
    "invoke_tool_handler",
]
